before_script:
  - cd ..
  - sudo add-apt-repository --yes ppa:sonkun/sfml-development
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt4-qmake libsfml-dev libphysfs-dev libtinyxml-dev libglew-dev libopenal-dev
  - git clone https://github.com/Antidote/libzelda.git
  - cd libzelda
  - qmake libzelda.pro
  - make
  - cd ../Sakura

script:
  - qmake Sakura.pro
  - make

notifications:
  irc: "irc.wiiking.com#wiiking2"
